name: telegram-gpt
version: 1.0.0
node_version: "14.x"

routes:
  - route: /app.js
    serve: src/app.js
    allow: GET, POST, HEAD

  - route: /.*
    rewrite: src/index.html
    allow: GET, POST, HEAD
